- name: Add git apt repo
  become: yes
  apt_repository:
    repo: 'ppa:git-core/ppa'
    state: present
  notify: apt update

- name: Install git packages
  become: yes
  apt:
    name:
      - git
    state: latest
  tags:
    - install_git
