---
# roles/pg_backup/tasks/main.yml

- name: Add PosgreSQL apt repo
  become: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename}}-pgdg main' state=present
  when: "'pg_backup' in group_names"
  notify: apt update

- name: Add PosgreSQL apt key
  become: yes
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  when: "'pg_backup' in group_names"
  notify: apt update

- name: Install PostgreSQL server
  become: yes
  apt: name="postgresql-server-dev-{{ postgresql_version }}" state=present
  when: "'pg_backup' in group_names"

- name: Install PostgreSQL client
  become: yes
  apt: name="postgresql-{{ postgresql_version }}" state=present
  when: "'pg_backup' in group_names"

- import_tasks: backup.yml
  when: backup_postgres in ["plain", "dump"]
