[app1]
188.85.3.219

[app1:vars]
hostname='app1'
ansible_python_interpreter = '/usr/bin/python3'

[citusdb1]
188.85.3.219

[citusdb1:vars]
hostname='citusdb1'

[citusdb2]
188.85.3.219

[citusdb2:vars]
hostname='citusdb2'

[citusdb3]
188.85.3.219

[citusdb3:vars]
hostname='citusdb3'

[citusdb_worker]
188.85.3.219

[citusdb_worker:vars]
ansible_python_interpreter = '/usr/bin/python3'

[all]
pg1 ansible_host=188.85.3.219 ansible_python_interpreter=/usr/bin/python3

[citusdb_master]
pg1

[citusdb_worker]
pg1

[citusdb_master:vars]
ansible_python_interpreter = '/usr/bin/python3'

[db1]
188.85.3.219

[db1:vars]
hostname='db1'
ansible_python_interpreter = '/usr/bin/python3'

[proxy1]
188.85.3.219

[proxy1:vars]
hostname='proxy1'
ansible_python_interpreter = '/usr/bin/python3'

[webworkers]
188.85.3.219

[postgresql]
188.85.3.219

[postgresql:vars]
hot_standby_server="188.85.3.219"
postgresql_replication_slots="['standby1']"

[pg_standby]
188.85.3.219

[pg_standby:vars]
hot_standby_master="188.85.3.219"
replication_slot=standby1

[pg_backup]
188.85.3.219

[pg_backup:vars]
pg_backup_from="188.85.3.219"

[couchdb2]
188.85.3.219

[redis]
188.85.3.219

[redis_cluster_master]
188.85.3.219

[formplayer]
188.85.3.219

[celery]
188.85.3.219 datadog_integrations=celery

[elasticsearch]
188.85.3.219 elasticsearch_node_name=es0

[proxy]
188.85.3.219

[rabbitmq]
188.85.3.219

[zookeeper]
188.85.3.219

[kafka]
188.85.3.219 kafka_broker_id=0

[pillowtop]
188.85.3.219

[shared_dir_host]
188.85.3.219

[mailrelay]
188.85.3.219 parent_mailrelay='mail.example.org'

[couchdb2_proxy]
188.85.3.219

[control]
188.85.3.219

[control:vars]
hostname='control'

[django_manage:children]
webworkers