---
- name: Logstash (disabled)
  hosts: logproxy
  gather_facts: false
  tasks:
    - name: Logstash intentionally disabled for this environment
      debug:
        msg: "Logstash is disabled"
      tags: logstash

- name: FileBeat (disabled)
  hosts: proxy
  gather_facts: false
  tasks:
    - name: FileBeat intentionally disabled for this environment
      debug:
        msg: "FileBeat is disabled"
      tags: filebeat
