- name: restart rsyslog
  become: yes
  service: name=rsyslog state=restarted

- name: apt update
  become: yes
  shell: |
    while fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || \
          fuser /var/lib/dpkg/lock >/dev/null 2>&1 || \
          fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
      sleep 5
    done
    apt-get update
  args:
    executable: /bin/bash
